//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasaVendavel : Casa
    {
        public string ValorBaseVenda { get; set; }
        public string ValorComissao { get; set; }
    
        public virtual Venda Venda { get; set; }
    }
}
